# http://localhost:5000

GET http://localhost:5000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsIm5hbWUiOiJNaWthIE1hZGEiLCJlbWFpbCI6Im1pa2FtYWRhQG1haWwuY29tIiwiaWF0IjoxNjg2MDY0OTg1LCJleHAiOjE2ODYwNjUwMDV9.dN3cXVd7_buPC8HZYv0qSBRk-bW0oe6nlLVd7dcxOps

###
POST http://localhost:5000/users
Content-Type: application/json

{
  "name": "test2",
  "email": "test2@mail.com",
  "password": "123456",
  "confPassword": "123456"
}

###
POST http://localhost:5000/login
Content-Type: application/json

{
  "email": "test2@mail.com",
  "password": "123456",
}